---
- name: Auto Update Linux Servers
  hosts: all  # 针对清单中的所有主机
  become: true # 等同于 sudo，因为 yum 需要 root 权限
  gather_facts: false # 加快速度，不需要收集系统信息

  tasks:
    - name: Run yum update
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      register: yum_result

    - name: Print update summary
      ansible.builtin.debug:
        msg: "Update completed. Changed: {{ yum_result.changed }}, Failed: {{ yum_result.failed }}"